### ISSUE TITLE
$Headers in private\Invoke-AppVeyorApi.ps1 could be null

### ISSUE THREAD

**Issue by zhenl-microsoft** [dotps1/PSAppVeyor#4]
$Headers may not be initialized if not passed in as parameter and could causing errors as below:

PS > Start-AppVeyorProjectBuild -AccountName xxx -ProjectName yyy -Branch zzz -CommitId ttt
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PSAppVeyor\0.2.7\Private\Invoke-AppVeyorApi.ps1:56 char:9
+         $Headers.Add(
+         ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\PSAppVeyor\0.2.7\Private\Invoke-AppVeyorApi.ps1:59 char:9
+         $Headers.Add(
+         ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Invoke-AppVeyorApi : Authorization required
At C:\Program Files\WindowsPowerShell\Modules\PSAppVeyor\0.2.7\Public\Start-AppVeyorProjectBuild.ps1:95 char:18
+ ...            (Invoke-AppVeyorApi -Method 'POST' -RestMethod 'builds' -B ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-AppVeyorApi

BuildId           : 0
Jobs              :
BuildNumber       : 0
Version           :
Message           :
MessageExtended   :
Branch            :
CommitId          :
AuthorName        :
AuthorUserName    :
CommitterName     :
CommitterUserName :
Committed         :
Messages          :
Status            :
Started           :
Finished          :
Created           :
Updated           :

**Comment by zhenl-microsoft** [comment]
fixed.

**Comment by dotps1** [comment]
Merged and published to the PSGallery.  Thanks for you contribution.
